version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing requests library..."
      - pip install requests
      #- pip list  # Lists all installed packages to verify installation
  pre_build:
    commands:
      - echo "Entering pre_build phase..."
  build:
    commands:
      - echo "Running Python script to fetch a random joke..."
      - python your_script.py
  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - '**/*'
